"Filed out from Dolphin Smalltalk 7"!

Notification subclass: #SuccessNotification
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SuccessNotification guid: (GUID fromString: '{6CD438A8-82A9-4D92-8774-7E30704DB26A}')!
SuccessNotification comment: ''!
!SuccessNotification categoriesForClass!Kernel-Exception Handling! !
!SuccessNotification methodsFor!

defaultAction

	Sound informationBeep.
! !
!SuccessNotification categoriesFor: #defaultAction!public! !

